package eng.cpe.se.project.model;
// Generated Mar 1, 2023, 12:55:07 AM by Hibernate Tools 5.6.3.Final

/**
 * Bookmark generated by hbm2java
 */
public class Bookmark implements java.io.Serializable {

	private int bookmarkId;
	private Post post;
	private User user;

	public Bookmark() {
	}

	public Bookmark(Post post, User user) {
		this.post = post;
		this.user = user;
	}

	public int getBookmarkId() {
		return this.bookmarkId;
	}

	public void setBookmarkId(int bookmarkId) {
		this.bookmarkId = bookmarkId;
	}

	public Post getPost() {
		return this.post;
	}

	public void setPost(Post post) {
		this.post = post;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
