package eng.cpe.se.project.model;
// Generated Feb 24, 2023, 1:08:39 AM by Hibernate Tools 5.6.3.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Comment generated by hbm2java
 */
public class Comment implements java.io.Serializable {

	private int commentId;
	private Post post;
	private User user;
	private String commentDetail;
	private List<Report> reports = new ArrayList<Report>();
	private List<CommentLike> commentLikes = new ArrayList<CommentLike>();

	public Comment() {
	}

	public Comment(int commentId, Post post, User user, String commentDetail) {
		this.commentId = commentId;
		this.post = post;
		this.user = user;
		this.commentDetail = commentDetail;
	}

	public Comment(int commentId, Post post, User user, String commentDetail, List<Report> reports, List<CommentLike> commentlikes) {
		this.commentId = commentId;
		this.post = post;
		this.user = user;
		this.commentDetail = commentDetail;
		this.reports = reports;
		this.setCommentLikes(commentlikes);
	}

	public int getCommentId() {
		return this.commentId;
	}

	public void setCommentId(int commentId) {
		this.commentId = commentId;
	}

	public Post getPost() {
		return this.post;
	}

	public void setPost(Post post) {
		this.post = post;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getCommentDetail() {
		return this.commentDetail;
	}

	public void setCommentDetail(String commentDetail) {
		this.commentDetail = commentDetail;
	}

	public List<Report> getReports() {
		return this.reports;
	}

	public void setReports(List<Report> reports) {
		this.reports = reports;
	}

	public List<CommentLike> getCommentLikes() {
		return commentLikes;
	}

	public void setCommentLikes(List<CommentLike> commentLikes) {
		this.commentLikes = commentLikes;
	}

}
