package eng.cpe.se.project.model;
// Generated Mar 7, 2023, 9:28:55 AM by Hibernate Tools 5.6.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Comment generated by hbm2java
 */
public class Comment implements java.io.Serializable {

	private Integer commentId;
	private Post post;
	private User user;
	private String commentDetail;
	private String reportStatus;
	private Date createDate;
	private Set reports = new HashSet(0);
	private Set imgcomments = new HashSet(0);
	private Set likecomments = new HashSet(0);

	public Comment() {
	}

	public Comment(Post post, User user, String commentDetail, Date createDate) {
		this.post = post;
		this.user = user;
		this.commentDetail = commentDetail;
		this.createDate = createDate;
	}

	public Comment(Post post, User user, String commentDetail, String reportStatus, Date createDate, Set reports,
			Set imgcomments, Set likecomments) {
		this.post = post;
		this.user = user;
		this.commentDetail = commentDetail;
		this.reportStatus = reportStatus;
		this.createDate = createDate;
		this.reports = reports;
		this.imgcomments = imgcomments;
		this.likecomments = likecomments;
	}

	public Integer getCommentId() {
		return this.commentId;
	}

	public void setCommentId(Integer commentId) {
		this.commentId = commentId;
	}

	public Post getPost() {
		return this.post;
	}

	public void setPost(Post post) {
		this.post = post;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getCommentDetail() {
		return this.commentDetail;
	}

	public void setCommentDetail(String commentDetail) {
		this.commentDetail = commentDetail;
	}

	public String getReportStatus() {
		return this.reportStatus;
	}

	public void setReportStatus(String reportStatus) {
		this.reportStatus = reportStatus;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Set getReports() {
		return this.reports;
	}

	public void setReports(Set reports) {
		this.reports = reports;
	}

	public Set getImgcomments() {
		return this.imgcomments;
	}

	public void setImgcomments(Set imgcomments) {
		this.imgcomments = imgcomments;
	}

	public Set getLikecomments() {
		return this.likecomments;
	}

	public void setLikecomments(Set likecomments) {
		this.likecomments = likecomments;
	}

}
