package eng.cpe.se.project.model;
// Generated Mar 7, 2023, 9:28:55 AM by Hibernate Tools 5.6.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Contenttype generated by hbm2java
 */
public class Contenttype implements java.io.Serializable {

	private Integer contentTypeId;
	private String typeName;
	private Set courses = new HashSet(0);
	private Set posts = new HashSet(0);

	public Contenttype() {
	}

	public Contenttype(String typeName) {
		this.typeName = typeName;
	}

	public Contenttype(String typeName, Set courses, Set posts) {
		this.typeName = typeName;
		this.courses = courses;
		this.posts = posts;
	}

	public Integer getContentTypeId() {
		return this.contentTypeId;
	}

	public void setContentTypeId(Integer contentTypeId) {
		this.contentTypeId = contentTypeId;
	}

	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	public Set getCourses() {
		return this.courses;
	}

	public void setCourses(Set courses) {
		this.courses = courses;
	}

	public Set getPosts() {
		return this.posts;
	}

	public void setPosts(Set posts) {
		this.posts = posts;
	}

}
