package eng.cpe.se.project.model;
// Generated Mar 7, 2023, 9:28:55 AM by Hibernate Tools 5.6.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Course generated by hbm2java
 */
public class Course implements java.io.Serializable {

	private Integer courseId;
	private Contenttype contenttype;
	private User user;
	private String courseTopic;
	private String courseDetail;
	private int minimum;
	private int maximum;
	private double price;
	private String status;
	private String reportStatus;
	private Date firstEnrollDate;
	private Date lastEnrollDate;
	private Date eventDate;
	private Date startDate;
	private Date endDate;
	private Set reports = new HashSet(0);
	private Set imgcourses = new HashSet(0);
	private Set joincourses = new HashSet(0);

	public Course() {
	}

	public Course(Contenttype contenttype, User user, String courseTopic, String courseDetail, int minimum, int maximum,
			double price, String status, Date firstEnrollDate, Date lastEnrollDate, Date eventDate, Date startDate,
			Date endDate) {
		this.contenttype = contenttype;
		this.user = user;
		this.courseTopic = courseTopic;
		this.courseDetail = courseDetail;
		this.minimum = minimum;
		this.maximum = maximum;
		this.price = price;
		this.status = status;
		this.firstEnrollDate = firstEnrollDate;
		this.lastEnrollDate = lastEnrollDate;
		this.eventDate = eventDate;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	public Course(Contenttype contenttype, User user, String courseTopic, String courseDetail, int minimum, int maximum,
			double price, String status, String reportStatus, Date firstEnrollDate, Date lastEnrollDate, Date eventDate,
			Date startDate, Date endDate, Set reports, Set imgcourses, Set joincourses) {
		this.contenttype = contenttype;
		this.user = user;
		this.courseTopic = courseTopic;
		this.courseDetail = courseDetail;
		this.minimum = minimum;
		this.maximum = maximum;
		this.price = price;
		this.status = status;
		this.reportStatus = reportStatus;
		this.firstEnrollDate = firstEnrollDate;
		this.lastEnrollDate = lastEnrollDate;
		this.eventDate = eventDate;
		this.startDate = startDate;
		this.endDate = endDate;
		this.reports = reports;
		this.imgcourses = imgcourses;
		this.joincourses = joincourses;
	}

	public Integer getCourseId() {
		return this.courseId;
	}

	public void setCourseId(Integer courseId) {
		this.courseId = courseId;
	}

	public Contenttype getContenttype() {
		return this.contenttype;
	}

	public void setContenttype(Contenttype contenttype) {
		this.contenttype = contenttype;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getCourseTopic() {
		return this.courseTopic;
	}

	public void setCourseTopic(String courseTopic) {
		this.courseTopic = courseTopic;
	}

	public String getCourseDetail() {
		return this.courseDetail;
	}

	public void setCourseDetail(String courseDetail) {
		this.courseDetail = courseDetail;
	}

	public int getMinimum() {
		return this.minimum;
	}

	public void setMinimum(int minimum) {
		this.minimum = minimum;
	}

	public int getMaximum() {
		return this.maximum;
	}

	public void setMaximum(int maximum) {
		this.maximum = maximum;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getReportStatus() {
		return this.reportStatus;
	}

	public void setReportStatus(String reportStatus) {
		this.reportStatus = reportStatus;
	}

	public Date getFirstEnrollDate() {
		return this.firstEnrollDate;
	}

	public void setFirstEnrollDate(Date firstEnrollDate) {
		this.firstEnrollDate = firstEnrollDate;
	}

	public Date getLastEnrollDate() {
		return this.lastEnrollDate;
	}

	public void setLastEnrollDate(Date lastEnrollDate) {
		this.lastEnrollDate = lastEnrollDate;
	}

	public Date getEventDate() {
		return this.eventDate;
	}

	public void setEventDate(Date eventDate) {
		this.eventDate = eventDate;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Set getReports() {
		return this.reports;
	}

	public void setReports(Set reports) {
		this.reports = reports;
	}

	public Set getImgcourses() {
		return this.imgcourses;
	}

	public void setImgcourses(Set imgcourses) {
		this.imgcourses = imgcourses;
	}

	public Set getJoincourses() {
		return this.joincourses;
	}

	public void setJoincourses(Set joincourses) {
		this.joincourses = joincourses;
	}

}
