package eng.cpe.se.project.model;
// Generated Feb 24, 2023, 1:08:39 AM by Hibernate Tools 5.6.3.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Course generated by hbm2java
 */
public class Course implements java.io.Serializable {

	private int courseId;
	private CourseCreator courseCreator;
	private Post post;
	private Type type;
	private String courseDetail;
	private int minimum;
	private int maximum;
	private float price;
	private String status;
	private Date firstEnrollDate;
	private Date lastEnrollDate;
	private Date eventDay;
	private String startTime;
	private String endTime;
	private List<JoinCourse> joinCourses = new ArrayList<JoinCourse>();
	private List<Report> reports = new ArrayList<Report>();
	private List<RequestCourseDetail> requestCourseDetails = new ArrayList<RequestCourseDetail>();

	public Course() {
	}

	public Course(int courseId, CourseCreator coursecreator, Type type, String courseDetail, int minimum, float price,
			String status, Date firstEnrollDate, Date lastEnrollDate, Date eventDay, String startTime, String endTime) {
		this.courseId = courseId;
		this.courseCreator = coursecreator;
		this.type = type;
		this.courseDetail = courseDetail;
		this.minimum = minimum;
		this.price = price;
		this.status = status;
		this.firstEnrollDate = firstEnrollDate;
		this.lastEnrollDate = lastEnrollDate;
		this.eventDay = eventDay;
		this.startTime = startTime;
		this.endTime = endTime;
	}

	public Course(int courseId, CourseCreator coursecreator, Post post, Type type, String courseDetail, int minimum,
			Integer maximum, float price, String status, Date firstEnrollDate, Date lastEnrollDate, Date eventDay,
			String startTime, String endTime, List<JoinCourse> joincourses, List<Report> reports, List<RequestCourseDetail> requestcoursedetails) {
		this.courseId = courseId;
		this.courseCreator = coursecreator;
		this.post = post;
		this.type = type;
		this.courseDetail = courseDetail;
		this.minimum = minimum;
		this.maximum = maximum;
		this.price = price;
		this.status = status;
		this.firstEnrollDate = firstEnrollDate;
		this.lastEnrollDate = lastEnrollDate;
		this.eventDay = eventDay;
		this.startTime = startTime;
		this.endTime = endTime;
		this.setJoinCourses(joincourses);
		this.setReports(reports);
		this.setRequestCourseDetails(requestcoursedetails);
	}

	public int getCourseId() {
		return this.courseId;
	}

	public void setCourseId(int courseId) {
		this.courseId = courseId;
	}

	public CourseCreator getCourseCreator() {
		return this.courseCreator;
	}

	public void setCourseCreator(CourseCreator coursecreator) {
		this.courseCreator = coursecreator;
	}

	public Post getPost() {
		return this.post;
	}

	public void setPost(Post post) {
		this.post = post;
	}

	public Type getType() {
		return this.type;
	}

	public void setType(Type type) {
		this.type = type;
	}

	public String getCourseDetail() {
		return this.courseDetail;
	}

	public void setCourseDetail(String courseDetail) {
		this.courseDetail = courseDetail;
	}

	public int getMinimum() {
		return this.minimum;
	}

	public void setMinimum(int minimum) {
		this.minimum = minimum;
	}

	public Integer getMaximum() {
		return this.maximum;
	}

	public void setMaximum(Integer maximum) {
		this.maximum = maximum;
	}

	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getFirstEnrollDate() {
		return this.firstEnrollDate;
	}

	public void setFirstEnrollDate(Date firstEnrollDate) {
		this.firstEnrollDate = firstEnrollDate;
	}

	public Date getLastEnrollDate() {
		return this.lastEnrollDate;
	}

	public void setLastEnrollDate(Date lastEnrollDate) {
		this.lastEnrollDate = lastEnrollDate;
	}

	public Date getEventDay() {
		return this.eventDay;
	}

	public void setEventDay(Date eventDay) {
		this.eventDay = eventDay;
	}

	public String getStartTime() {
		return this.startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	public String getEndTime() {
		return this.endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public List<JoinCourse> getJoinCourses() {
		return joinCourses;
	}

	public void setJoinCourses(List<JoinCourse> joinCourses) {
		this.joinCourses = joinCourses;
	}

	public List<Report> getReports() {
		return reports;
	}

	public void setReports(List<Report> reports) {
		this.reports = reports;
	}

	public List<RequestCourseDetail> getRequestCourseDetails() {
		return requestCourseDetails;
	}

	public void setRequestCourseDetails(List<RequestCourseDetail> requestCourseDetails) {
		this.requestCourseDetails = requestCourseDetails;
	}

}
