package eng.cpe.se.project.model;
// Generated Mar 7, 2023, 9:28:55 AM by Hibernate Tools 5.6.3.Final

/**
 * Follower generated by hbm2java
 */
public class Follower implements java.io.Serializable {

	private Integer followerId;
	private User userByFollowTo;
	private User userByFollowBy;

	public Follower() {
	}

	public Follower(User userByFollowTo, User userByFollowBy) {
		this.userByFollowTo = userByFollowTo;
		this.userByFollowBy = userByFollowBy;
	}

	public Integer getFollowerId() {
		return this.followerId;
	}

	public void setFollowerId(Integer followerId) {
		this.followerId = followerId;
	}

	public User getUserByFollowTo() {
		return this.userByFollowTo;
	}

	public void setUserByFollowTo(User userByFollowTo) {
		this.userByFollowTo = userByFollowTo;
	}

	public User getUserByFollowBy() {
		return this.userByFollowBy;
	}

	public void setUserByFollowBy(User userByFollowBy) {
		this.userByFollowBy = userByFollowBy;
	}

}
