package eng.cpe.se.project.model;
// Generated Mar 1, 2023, 12:55:07 AM by Hibernate Tools 5.6.3.Final

/**
 * Imgcomment generated by hbm2java
 */
public class ImgComment implements java.io.Serializable {

	private int imgComment;
	private Comment comment;
	private String imgPath;

	public ImgComment() {
	}

	public ImgComment(Comment comment, String imgPath) {
		this.comment = comment;
		this.imgPath = imgPath;
	}

	public int getImgComment() {
		return imgComment;
	}

	public void setImgComment(int imgComment) {
		this.imgComment = imgComment;
	}

	public Comment getComment() {
		return comment;
	}

	public void setComment(Comment comment) {
		this.comment = comment;
	}

	public String getImgPath() {
		return imgPath;
	}

	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}

	

}
