package eng.cpe.se.project.model;
// Generated Mar 5, 2023, 12:22:12 AM by Hibernate Tools 5.6.3.Final

/**
 * Imgcomment generated by hbm2java
 */
public class ImgComment implements java.io.Serializable {

	private int imgCommentId;
	private Comment comment;
	private String imgPath;

	public ImgComment() {
	}

	public ImgComment(Comment comment, String imgPath) {
		this.comment = comment;
		this.imgPath = imgPath;
	}

	public int getImgCommentId() {
		return this.imgCommentId;
	}

	public void setImgCommentId(int imgCommentId) {
		this.imgCommentId = imgCommentId;
	}

	public Comment getComment() {
		return this.comment;
	}

	public void setComment(Comment comment) {
		this.comment = comment;
	}

	public String getImgPath() {
		return this.imgPath;
	}

	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}

}
