package eng.cpe.se.project.model;
// Generated Mar 7, 2023, 9:28:55 AM by Hibernate Tools 5.6.3.Final

/**
 * Imgcomment generated by hbm2java
 */
public class Imgcomment implements java.io.Serializable {

	private Integer imgCommentId;
	private Comment comment;
	private String imgPath;

	public Imgcomment() {
	}

	public Imgcomment(Comment comment, String imgPath) {
		this.comment = comment;
		this.imgPath = imgPath;
	}

	public Integer getImgCommentId() {
		return this.imgCommentId;
	}

	public void setImgCommentId(Integer imgCommentId) {
		this.imgCommentId = imgCommentId;
	}

	public Comment getComment() {
		return this.comment;
	}

	public void setComment(Comment comment) {
		this.comment = comment;
	}

	public String getImgPath() {
		return this.imgPath;
	}

	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}

}
