package eng.cpe.se.project.model;
// Generated Mar 7, 2023, 9:28:55 AM by Hibernate Tools 5.6.3.Final

/**
 * Imgpost generated by hbm2java
 */
public class Imgpost implements java.io.Serializable {

	private Integer imgPostId;
	private Post post;
	private String imgPath;

	public Imgpost() {
	}

	public Imgpost(Post post, String imgPath) {
		this.post = post;
		this.imgPath = imgPath;
	}

	public Integer getImgPostId() {
		return this.imgPostId;
	}

	public void setImgPostId(Integer imgPostId) {
		this.imgPostId = imgPostId;
	}

	public Post getPost() {
		return this.post;
	}

	public void setPost(Post post) {
		this.post = post;
	}

	public String getImgPath() {
		return this.imgPath;
	}

	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}

}
