package eng.cpe.se.project.model;
// Generated Mar 7, 2023, 9:28:55 AM by Hibernate Tools 5.6.3.Final

/**
 * Imgverify generated by hbm2java
 */
public class Imgverify implements java.io.Serializable {

	private Integer imgVerifyId;
	private Requestverify requestverify;
	private String imgPath;

	public Imgverify() {
	}

	public Imgverify(Requestverify requestverify, String imgPath) {
		this.requestverify = requestverify;
		this.imgPath = imgPath;
	}

	public Integer getImgVerifyId() {
		return this.imgVerifyId;
	}

	public void setImgVerifyId(Integer imgVerifyId) {
		this.imgVerifyId = imgVerifyId;
	}

	public Requestverify getRequestverify() {
		return this.requestverify;
	}

	public void setRequestverify(Requestverify requestverify) {
		this.requestverify = requestverify;
	}

	public String getImgPath() {
		return this.imgPath;
	}

	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}

}
