package eng.cpe.se.project.model;
// Generated Mar 5, 2023, 12:22:12 AM by Hibernate Tools 5.6.3.Final

/**
 * Joincourse generated by hbm2java
 */
public class JoinCourse implements java.io.Serializable {

	private int joinCourseId;
	private Course course;
	private User user;

	public JoinCourse() {
	}

	public JoinCourse(Course course, User user) {
		this.course = course;
		this.user = user;
	}

	public int getJoinCourseId() {
		return this.joinCourseId;
	}

	public void setJoinCourseId(int joinCourseId) {
		this.joinCourseId = joinCourseId;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
