package eng.cpe.se.project.model;
// Generated Feb 24, 2023, 1:08:39 AM by Hibernate Tools 5.6.3.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Joincourse generated by hbm2java
 */
public class JoinCourse implements java.io.Serializable {

	private int joinCourseId;
	private Course course;
	private List<PaymentCheck> paymentChecks = new ArrayList<PaymentCheck>();

	public JoinCourse() {
	}

	public JoinCourse(int joinCourseId, Course course) {
		this.joinCourseId = joinCourseId;
		this.course = course;
	}

	public JoinCourse(int joinCourseId, Course course, List<PaymentCheck> paymentchecks) {
		this.joinCourseId = joinCourseId;
		this.course = course;
		this.setPaymentChecks(paymentchecks);
	}

	public int getJoinCourseId() {
		return this.joinCourseId;
	}

	public void setJoinCourseId(int joinCourseId) {
		this.joinCourseId = joinCourseId;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public List<PaymentCheck> getPaymentChecks() {
		return paymentChecks;
	}

	public void setPaymentChecks(List<PaymentCheck> paymentChecks) {
		this.paymentChecks = paymentChecks;
	}


}
