package eng.cpe.se.project.model;
// Generated Mar 7, 2023, 9:28:55 AM by Hibernate Tools 5.6.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Joincourse generated by hbm2java
 */
public class Joincourse implements java.io.Serializable {

	private Integer joinCourseId;
	private Course course;
	private Set paymentchecks = new HashSet(0);

	public Joincourse() {
	}

	public Joincourse(Course course) {
		this.course = course;
	}

	public Joincourse(Course course, Set paymentchecks) {
		this.course = course;
		this.paymentchecks = paymentchecks;
	}

	public Integer getJoinCourseId() {
		return this.joinCourseId;
	}

	public void setJoinCourseId(Integer joinCourseId) {
		this.joinCourseId = joinCourseId;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public Set getPaymentchecks() {
		return this.paymentchecks;
	}

	public void setPaymentchecks(Set paymentchecks) {
		this.paymentchecks = paymentchecks;
	}

}
