package eng.cpe.se.project.model;
// Generated Mar 7, 2023, 9:28:55 AM by Hibernate Tools 5.6.3.Final

/**
 * Likecomment generated by hbm2java
 */
public class Likecomment implements java.io.Serializable {

	private Integer likeCommentId;
	private Comment comment;
	private User user;

	public Likecomment() {
	}

	public Likecomment(Comment comment, User user) {
		this.comment = comment;
		this.user = user;
	}

	public Integer getLikeCommentId() {
		return this.likeCommentId;
	}

	public void setLikeCommentId(Integer likeCommentId) {
		this.likeCommentId = likeCommentId;
	}

	public Comment getComment() {
		return this.comment;
	}

	public void setComment(Comment comment) {
		this.comment = comment;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
