package eng.cpe.se.project.model;
// Generated Mar 7, 2023, 9:28:55 AM by Hibernate Tools 5.6.3.Final

/**
 * Likepost generated by hbm2java
 */
public class Likepost implements java.io.Serializable {

	private Integer likePostId;
	private Post post;
	private User user;

	public Likepost() {
	}

	public Likepost(Post post, User user) {
		this.post = post;
		this.user = user;
	}

	public Integer getLikePostId() {
		return this.likePostId;
	}

	public void setLikePostId(Integer likePostId) {
		this.likePostId = likePostId;
	}

	public Post getPost() {
		return this.post;
	}

	public void setPost(Post post) {
		this.post = post;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
