package eng.cpe.se.project.model;
// Generated Mar 7, 2023, 9:28:55 AM by Hibernate Tools 5.6.3.Final

/**
 * Paymentcheck generated by hbm2java
 */
public class Paymentcheck implements java.io.Serializable {

	private Integer paymentCheckId;
	private Joincourse joincourse;
	private User user;
	private String imgPath;

	public Paymentcheck() {
	}

	public Paymentcheck(Joincourse joincourse, User user, String imgPath) {
		this.joincourse = joincourse;
		this.user = user;
		this.imgPath = imgPath;
	}

	public Integer getPaymentCheckId() {
		return this.paymentCheckId;
	}

	public void setPaymentCheckId(Integer paymentCheckId) {
		this.paymentCheckId = paymentCheckId;
	}

	public Joincourse getJoincourse() {
		return this.joincourse;
	}

	public void setJoincourse(Joincourse joincourse) {
		this.joincourse = joincourse;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getImgPath() {
		return this.imgPath;
	}

	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}

}
