package eng.cpe.se.project.model;
// Generated Feb 24, 2023, 1:08:39 AM by Hibernate Tools 5.6.3.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Post generated by hbm2java
 */
public class Post implements java.io.Serializable {

	private int postId;
	private Type type;
	private User user;
	private String postDetail;
	private String imgPath;
	private List<Report> reports = new ArrayList<Report>();
	private List<RequestCourse> requestCourses = new ArrayList<RequestCourse>();
	private List<PostLike> postLikes = new ArrayList<PostLike>();
	private List<Comment> comments = new ArrayList<Comment>();
	private List<Bookmark> bookmarks = new ArrayList<Bookmark>();
	private List<Course> courses = new ArrayList<Course>();

	public Post() {
	}

	public Post(int postId, User user, String postDetail, String imgPath) {
		this.setPostId(postId);
		this.setUser(user);
		this.setPostDetail(postDetail);
		this.setImgPath(imgPath);
	}

	public Post(int postId, Type type, User user, String postDetail, String imgPath, List<Report> reports, List<RequestCourse> requestcourses,
			List<PostLike> postlikes, List<Comment> comments, List<Bookmark> bookmarks, List<Course> courses) {
		this.setPostId(postId);
		this.setType(type);
		this.setUser(user);
		this.setPostDetail(postDetail);
		this.setImgPath(imgPath);
		this.setReports(reports);
		this.setRequestCourses(requestcourses);
		this.setPostLikes(postlikes);
		this.setComments(comments);
		this.setBookmarks(bookmarks);
		this.setCourses(courses);
	}

	public int getPostId() {
		return postId;
	}

	public void setPostId(int postId) {
		this.postId = postId;
	}

	public Type getType() {
		return type;
	}

	public void setType(Type type) {
		this.type = type;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getPostDetail() {
		return postDetail;
	}

	public void setPostDetail(String postDetail) {
		this.postDetail = postDetail;
	}

	public String getImgPath() {
		return imgPath;
	}

	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}

	public List<Report> getReports() {
		return reports;
	}

	public void setReports(List<Report> reports) {
		this.reports = reports;
	}

	public List<RequestCourse> getRequestCourses() {
		return requestCourses;
	}

	public void setRequestCourses(List<RequestCourse> requestCourses) {
		this.requestCourses = requestCourses;
	}

	public List<PostLike> getPostLikes() {
		return postLikes;
	}

	public void setPostLikes(List<PostLike> postLikes) {
		this.postLikes = postLikes;
	}

	public List<Comment> getComments() {
		return comments;
	}

	public void setComments(List<Comment> comments) {
		this.comments = comments;
	}

	public List<Bookmark> getBookmarks() {
		return bookmarks;
	}

	public void setBookmarks(List<Bookmark> bookmarks) {
		this.bookmarks = bookmarks;
	}

	public List<Course> getCourses() {
		return courses;
	}

	public void setCourses(List<Course> courses) {
		this.courses = courses;
	}

}
