package eng.cpe.se.project.model;
// Generated Mar 7, 2023, 9:28:55 AM by Hibernate Tools 5.6.3.Final

/**
 * Report generated by hbm2java
 */
public class Report implements java.io.Serializable {

	private Integer reportId;
	private Comment comment;
	private Course course;
	private Post post;
	private Reporttype reporttype;
	private User user;
	private String reportDetail;
	private String status;

	public Report() {
	}

	public Report(Reporttype reporttype, User user, String reportDetail, String status) {
		this.reporttype = reporttype;
		this.user = user;
		this.reportDetail = reportDetail;
		this.status = status;
	}

	public Report(Comment comment, Course course, Post post, Reporttype reporttype, User user, String reportDetail,
			String status) {
		this.comment = comment;
		this.course = course;
		this.post = post;
		this.reporttype = reporttype;
		this.user = user;
		this.reportDetail = reportDetail;
		this.status = status;
	}

	public Integer getReportId() {
		return this.reportId;
	}

	public void setReportId(Integer reportId) {
		this.reportId = reportId;
	}

	public Comment getComment() {
		return this.comment;
	}

	public void setComment(Comment comment) {
		this.comment = comment;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public Post getPost() {
		return this.post;
	}

	public void setPost(Post post) {
		this.post = post;
	}

	public Reporttype getReporttype() {
		return this.reporttype;
	}

	public void setReporttype(Reporttype reporttype) {
		this.reporttype = reporttype;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getReportDetail() {
		return this.reportDetail;
	}

	public void setReportDetail(String reportDetail) {
		this.reportDetail = reportDetail;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
