package eng.cpe.se.project.model;
// Generated Mar 5, 2023, 12:22:12 AM by Hibernate Tools 5.6.3.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Reporttype generated by hbm2java
 */
public class ReportType implements java.io.Serializable {

	private int reportTypeId;
	private String typeName;
	private List<Report> reports = new ArrayList<Report>();

	public ReportType() {
	}

	public ReportType(String typeName) {
		this.typeName = typeName;
	}

	public ReportType(String typeName, List<Report> reports) {
		this.typeName = typeName;
		this.reports = reports;
	}

	public int getReportTypeId() {
		return reportTypeId;
	}

	public void setReportTypeId(int reportTypeId) {
		this.reportTypeId = reportTypeId;
	}

	public String getTypeName() {
		return typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	public List<Report> getReports() {
		return reports;
	}

	public void setReports(List<Report> reports) {
		this.reports = reports;
	}


}
