package eng.cpe.se.project.model;
// Generated Mar 7, 2023, 9:28:55 AM by Hibernate Tools 5.6.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Reporttype generated by hbm2java
 */
public class Reporttype implements java.io.Serializable {

	private Integer reportTypeId;
	private String typeName;
	private Set reports = new HashSet(0);

	public Reporttype() {
	}

	public Reporttype(String typeName) {
		this.typeName = typeName;
	}

	public Reporttype(String typeName, Set reports) {
		this.typeName = typeName;
		this.reports = reports;
	}

	public Integer getReportTypeId() {
		return this.reportTypeId;
	}

	public void setReportTypeId(Integer reportTypeId) {
		this.reportTypeId = reportTypeId;
	}

	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	public Set getReports() {
		return this.reports;
	}

	public void setReports(Set reports) {
		this.reports = reports;
	}

}
