package eng.cpe.se.project.model;
// Generated Mar 5, 2023, 12:22:12 AM by Hibernate Tools 5.6.3.Final

/**
 * Report generated by hbm2java
 */
public class Report implements java.io.Serializable {

	private int reportId;
	private Comment comment;
	private Course course;
	private Post post;
	private ReportType reportType;
	private User user;
	private String reportDetail;

	public Report() {
	}

	public Report(ReportType reporttype, User user, String reportDetail) {
		this.reportType = reporttype;
		this.user = user;
		this.reportDetail = reportDetail;
	}

	public Report(Comment comment, Course course, Post post, ReportType reporttype, User user, String reportDetail) {
		this.comment = comment;
		this.course = course;
		this.post = post;
		this.reportType = reporttype;
		this.user = user;
		this.reportDetail = reportDetail;
	}

	public int getReportId() {
		return reportId;
	}

	public void setReportId(int reportId) {
		this.reportId = reportId;
	}

	public Comment getComment() {
		return comment;
	}

	public void setComment(Comment comment) {
		this.comment = comment;
	}

	public Course getCourse() {
		return course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public Post getPost() {
		return post;
	}

	public void setPost(Post post) {
		this.post = post;
	}

	public ReportType getReportType() {
		return reportType;
	}

	public void setReportType(ReportType reportType) {
		this.reportType = reportType;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getReportDetail() {
		return reportDetail;
	}

	public void setReportDetail(String reportDetail) {
		this.reportDetail = reportDetail;
	}


}
