package eng.cpe.se.project.model;
// Generated Mar 1, 2023, 12:55:07 AM by Hibernate Tools 5.6.3.Final

/**
 * Requestverifydetail generated by hbm2java
 */
public class RequestVerifyDetail implements java.io.Serializable {

	private int requestVerifyDetail;
	private RequestVerify requestVerify;
	private User user;

	public RequestVerifyDetail() {
	}

	public RequestVerifyDetail(RequestVerify requestverify, User user) {
		this.requestVerify = requestverify;
		this.user = user;
	}

	public int getRequestVerifyDetail() {
		return requestVerifyDetail;
	}

	public void setRequestVerifyDetail(int requestVerifyDetail) {
		this.requestVerifyDetail = requestVerifyDetail;
	}

	public RequestVerify getRequestVerify() {
		return requestVerify;
	}

	public void setRequestVerify(RequestVerify requestVerify) {
		this.requestVerify = requestVerify;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}
	

}
