package eng.cpe.se.project.model;
// Generated Mar 7, 2023, 9:28:55 AM by Hibernate Tools 5.6.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Requestverify generated by hbm2java
 */
public class Requestverify implements java.io.Serializable {

	private Integer requestVerifyId;
	private Staff staff;
	private User user;
	private String verifyHeader;
	private String verifyDetail;
	private String approveStatus;
	private Date dateApprove;
	private Set imgverifies = new HashSet(0);

	public Requestverify() {
	}

	public Requestverify(Staff staff, User user, String verifyHeader, String verifyDetail, String approveStatus,
			Date dateApprove) {
		this.staff = staff;
		this.user = user;
		this.verifyHeader = verifyHeader;
		this.verifyDetail = verifyDetail;
		this.approveStatus = approveStatus;
		this.dateApprove = dateApprove;
	}

	public Requestverify(Staff staff, User user, String verifyHeader, String verifyDetail, String approveStatus,
			Date dateApprove, Set imgverifies) {
		this.staff = staff;
		this.user = user;
		this.verifyHeader = verifyHeader;
		this.verifyDetail = verifyDetail;
		this.approveStatus = approveStatus;
		this.dateApprove = dateApprove;
		this.imgverifies = imgverifies;
	}

	public Integer getRequestVerifyId() {
		return this.requestVerifyId;
	}

	public void setRequestVerifyId(Integer requestVerifyId) {
		this.requestVerifyId = requestVerifyId;
	}

	public Staff getStaff() {
		return this.staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getVerifyHeader() {
		return this.verifyHeader;
	}

	public void setVerifyHeader(String verifyHeader) {
		this.verifyHeader = verifyHeader;
	}

	public String getVerifyDetail() {
		return this.verifyDetail;
	}

	public void setVerifyDetail(String verifyDetail) {
		this.verifyDetail = verifyDetail;
	}

	public String getApproveStatus() {
		return this.approveStatus;
	}

	public void setApproveStatus(String approveStatus) {
		this.approveStatus = approveStatus;
	}

	public Date getDateApprove() {
		return this.dateApprove;
	}

	public void setDateApprove(Date dateApprove) {
		this.dateApprove = dateApprove;
	}

	public Set getImgverifies() {
		return this.imgverifies;
	}

	public void setImgverifies(Set imgverifies) {
		this.imgverifies = imgverifies;
	}

}
