package eng.cpe.se.project.model;
// Generated Mar 5, 2023, 12:22:12 AM by Hibernate Tools 5.6.3.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Requestverify generated by hbm2java
 */
public class RequestVerify implements java.io.Serializable {

	private int requestVerifyId;
	private Staff staff;
	private User user;
	private String verifyHeader;
	private String verifyDetail;
	private String approveStatus;
	private Date dateApprove;
	private List<ImgVerify> imgVerifies = new ArrayList<ImgVerify>();

	public RequestVerify() {
	}

	public RequestVerify(Staff staff, User user, String verifyHeader, String verifyDetail, String approveStatus,
			Date dateApprove) {
		this.staff = staff;
		this.user = user;
		this.verifyHeader = verifyHeader;
		this.verifyDetail = verifyDetail;
		this.approveStatus = approveStatus;
		this.dateApprove = dateApprove;
	}

	public RequestVerify(Staff staff, User user, String verifyHeader, String verifyDetail, String approveStatus,
			Date dateApprove, List<ImgVerify> imgverifies) {
		this.staff = staff;
		this.user = user;
		this.verifyHeader = verifyHeader;
		this.verifyDetail = verifyDetail;
		this.approveStatus = approveStatus;
		this.dateApprove = dateApprove;
		this.imgVerifies = imgverifies;
	}

	public int getRequestVerifyId() {
		return requestVerifyId;
	}

	public void setRequestVerifyId(int requestVerifyId) {
		this.requestVerifyId = requestVerifyId;
	}

	public Staff getStaff() {
		return staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getVerifyHeader() {
		return verifyHeader;
	}

	public void setVerifyHeader(String verifyHeader) {
		this.verifyHeader = verifyHeader;
	}

	public String getVerifyDetail() {
		return verifyDetail;
	}

	public void setVerifyDetail(String verifyDetail) {
		this.verifyDetail = verifyDetail;
	}

	public String getApproveStatus() {
		return approveStatus;
	}

	public void setApproveStatus(String approveStatus) {
		this.approveStatus = approveStatus;
	}

	public Date getDateApprove() {
		return dateApprove;
	}

	public void setDateApprove(Date dateApprove) {
		this.dateApprove = dateApprove;
	}

	public List<ImgVerify> getImgVerifies() {
		return imgVerifies;
	}

	public void setImgVerifies(List<ImgVerify> imgVerifies) {
		this.imgVerifies = imgVerifies;
	}


}
