package eng.cpe.se.project.model;
// Generated Mar 1, 2023, 12:55:07 AM by Hibernate Tools 5.6.3.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Requestverify generated by hbm2java
 */
public class RequestVerify implements java.io.Serializable {

	private int requestVerifyId;
	private Staff staff;
	private String status;
	private String note;
	private String imgPath;
	private List<RequestVerifyDetail> requestVerifyDetails = new ArrayList<RequestVerifyDetail>();
	private List<ImgVerify> imgVerifies = new ArrayList<ImgVerify>();

	public RequestVerify() {
	}

	public RequestVerify(Staff staff, String status, String note, String imgPath) {
		this.staff = staff;
		this.status = status;
		this.note = note;
		this.imgPath = imgPath;
	}

	public RequestVerify(Staff staff, String status, String note, String imgPath, List<RequestVerifyDetail> requestverifydetails,
			List<ImgVerify> imgverifies) {
		this.staff = staff;
		this.status = status;
		this.note = note;
		this.imgPath = imgPath;
		this.requestVerifyDetails = requestverifydetails;
		this.imgVerifies = imgverifies;
	}

	public int getRequestVerifyId() {
		return requestVerifyId;
	}

	public void setRequestVerifyId(int requestVerifyId) {
		this.requestVerifyId = requestVerifyId;
	}

	public Staff getStaff() {
		return staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getNote() {
		return note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public String getImgPath() {
		return imgPath;
	}

	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}

	public List<RequestVerifyDetail> getRequestVerifyDetails() {
		return requestVerifyDetails;
	}

	public void setRequestVerifyDetails(List<RequestVerifyDetail> requestVerifyDetails) {
		this.requestVerifyDetails = requestVerifyDetails;
	}

	public List<ImgVerify> getImgVerifies() {
		return imgVerifies;
	}

	public void setImgVerifies(List<ImgVerify> imgVerifies) {
		this.imgVerifies = imgVerifies;
	}
	

}
