package eng.cpe.se.project.model;
// Generated Feb 24, 2023, 1:08:39 AM by Hibernate Tools 5.6.3.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Requestverify generated by hbm2java
 */
public class RequestVerify implements java.io.Serializable {

	private int requestVerifyId;
	private Staff staff;
	private String status;
	private String note;
	private String imgPath;
	private List<RequestVerifyDetail> requestVerifyDetails = new ArrayList<RequestVerifyDetail>();

	public RequestVerify() {
	}

	public RequestVerify(int requestVerifyId, Staff staff, String status, String note, String imgPath) {
		this.requestVerifyId = requestVerifyId;
		this.staff = staff;
		this.status = status;
		this.note = note;
		this.imgPath = imgPath;
	}

	public RequestVerify(int requestVerifyId, Staff staff, String status, String note, String imgPath,
			List<RequestVerifyDetail> requestverifydetails) {
		this.requestVerifyId = requestVerifyId;
		this.staff = staff;
		this.status = status;
		this.note = note;
		this.imgPath = imgPath;
		this.setRequestVerifyDetails(requestverifydetails);
	}

	public int getRequestVerifyId() {
		return this.requestVerifyId;
	}

	public void setRequestVerifyId(int requestVerifyId) {
		this.requestVerifyId = requestVerifyId;
	}

	public Staff getStaff() {
		return this.staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public String getImgPath() {
		return this.imgPath;
	}

	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}

	public List<RequestVerifyDetail> getRequestVerifyDetails() {
		return requestVerifyDetails;
	}

	public void setRequestVerifyDetails(List<RequestVerifyDetail> requestVerifyDetails) {
		this.requestVerifyDetails = requestVerifyDetails;
	}


}
