package eng.cpe.se.project.model;
// Generated Feb 24, 2023, 1:08:39 AM by Hibernate Tools 5.6.3.Final

/**
 * Requestverifydetail generated by hbm2java
 */
public class RequestVerifyDetail implements java.io.Serializable {

	private int requestVerifyDetail;
	private RequestVerify requestVerify;
	private User user;

	public RequestVerifyDetail() {
	}

	public RequestVerifyDetail(int requestVerifyDetail, RequestVerify requestverify, User user) {
		this.requestVerifyDetail = requestVerifyDetail;
		this.requestVerify = requestverify;
		this.user = user;
	}

	public int getRequestVerifyDetail() {
		return this.requestVerifyDetail;
	}

	public void setRequestVerifyDetail(int requestVerifyDetail) {
		this.requestVerifyDetail = requestVerifyDetail;
	}

	public RequestVerify getRequestverify() {
		return this.requestVerify;
	}

	public void setRequestverify(RequestVerify requestverify) {
		this.requestVerify = requestverify;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
