package eng.cpe.se.project.model;
// Generated Mar 7, 2023, 9:28:55 AM by Hibernate Tools 5.6.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Staff generated by hbm2java
 */
public class Staff implements java.io.Serializable {

	private int staffId;
	private Account account;
	private String position;
	private Set requestverifies = new HashSet(0);

	public Staff() {
	}

	public Staff(Account account, String position) {
		this.account = account;
		this.position = position;
	}

	public Staff(Account account, String position, Set requestverifies) {
		this.account = account;
		this.position = position;
		this.requestverifies = requestverifies;
	}

	public int getStaffId() {
		return this.staffId;
	}

	public void setStaffId(int staffId) {
		this.staffId = staffId;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public Set getRequestverifies() {
		return this.requestverifies;
	}

	public void setRequestverifies(Set requestverifies) {
		this.requestverifies = requestverifies;
	}

}
