package eng.cpe.se.project.model;
// Generated Mar 7, 2023, 9:28:55 AM by Hibernate Tools 5.6.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private int userId;
	private Account account;
	private String username;
	private String imgPath;
	private String backgroundPath;
	private String verifyStatus;
	private String type;
	private Set comments = new HashSet(0);
	private Set likecomments = new HashSet(0);
	private Set followersForFollowTo = new HashSet(0);
	private Set followersForFollowBy = new HashSet(0);
	private Set paymentchecks = new HashSet(0);
	private Set posts = new HashSet(0);
	private Set requestcourses = new HashSet(0);
	private Set likeposts = new HashSet(0);
	private Set courses = new HashSet(0);
	private Set reports = new HashSet(0);
	private Set bookmarks = new HashSet(0);
	private Set requestverifies = new HashSet(0);

	public User() {
	}

	public User(Account account, String username, String imgPath, String backgroundPath, String verifyStatus,
			String type) {
		this.account = account;
		this.username = username;
		this.imgPath = imgPath;
		this.backgroundPath = backgroundPath;
		this.verifyStatus = verifyStatus;
		this.type = type;
	}

	public User(Account account, String username, String imgPath, String backgroundPath, String verifyStatus,
			String type, Set comments, Set likecomments, Set followersForFollowTo, Set followersForFollowBy,
			Set paymentchecks, Set posts, Set requestcourses, Set likeposts, Set courses, Set reports, Set bookmarks,
			Set requestverifies) {
		this.account = account;
		this.username = username;
		this.imgPath = imgPath;
		this.backgroundPath = backgroundPath;
		this.verifyStatus = verifyStatus;
		this.type = type;
		this.comments = comments;
		this.likecomments = likecomments;
		this.followersForFollowTo = followersForFollowTo;
		this.followersForFollowBy = followersForFollowBy;
		this.paymentchecks = paymentchecks;
		this.posts = posts;
		this.requestcourses = requestcourses;
		this.likeposts = likeposts;
		this.courses = courses;
		this.reports = reports;
		this.bookmarks = bookmarks;
		this.requestverifies = requestverifies;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getImgPath() {
		return this.imgPath;
	}

	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}

	public String getBackgroundPath() {
		return this.backgroundPath;
	}

	public void setBackgroundPath(String backgroundPath) {
		this.backgroundPath = backgroundPath;
	}

	public String getVerifyStatus() {
		return this.verifyStatus;
	}

	public void setVerifyStatus(String verifyStatus) {
		this.verifyStatus = verifyStatus;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Set getComments() {
		return this.comments;
	}

	public void setComments(Set comments) {
		this.comments = comments;
	}

	public Set getLikecomments() {
		return this.likecomments;
	}

	public void setLikecomments(Set likecomments) {
		this.likecomments = likecomments;
	}

	public Set getFollowersForFollowTo() {
		return this.followersForFollowTo;
	}

	public void setFollowersForFollowTo(Set followersForFollowTo) {
		this.followersForFollowTo = followersForFollowTo;
	}

	public Set getFollowersForFollowBy() {
		return this.followersForFollowBy;
	}

	public void setFollowersForFollowBy(Set followersForFollowBy) {
		this.followersForFollowBy = followersForFollowBy;
	}

	public Set getPaymentchecks() {
		return this.paymentchecks;
	}

	public void setPaymentchecks(Set paymentchecks) {
		this.paymentchecks = paymentchecks;
	}

	public Set getPosts() {
		return this.posts;
	}

	public void setPosts(Set posts) {
		this.posts = posts;
	}

	public Set getRequestcourses() {
		return this.requestcourses;
	}

	public void setRequestcourses(Set requestcourses) {
		this.requestcourses = requestcourses;
	}

	public Set getLikeposts() {
		return this.likeposts;
	}

	public void setLikeposts(Set likeposts) {
		this.likeposts = likeposts;
	}

	public Set getCourses() {
		return this.courses;
	}

	public void setCourses(Set courses) {
		this.courses = courses;
	}

	public Set getReports() {
		return this.reports;
	}

	public void setReports(Set reports) {
		this.reports = reports;
	}

	public Set getBookmarks() {
		return this.bookmarks;
	}

	public void setBookmarks(Set bookmarks) {
		this.bookmarks = bookmarks;
	}

	public Set getRequestverifies() {
		return this.requestverifies;
	}

	public void setRequestverifies(Set requestverifies) {
		this.requestverifies = requestverifies;
	}

}
