package eng.cpe.se.project.model;
// Generated Feb 24, 2023, 1:08:39 AM by Hibernate Tools 5.6.3.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private int userId;
	private Account account;
	private User user;
	private String userName;
	private String verifyStatus;
	private String imgPath;
	private List<Bookmark> bookmarks = new ArrayList<Bookmark>();
	private List<RequestVerifyDetail> requestVerifyDetails = new ArrayList<RequestVerifyDetail>();
	private List<PostLike> postLikes = new ArrayList<PostLike>();
	private List<CommentLike> commentLikes = new ArrayList<CommentLike>();
	private List<Post> posts = new ArrayList<Post>();
	private List<PaymentCheck> paymentChecks = new ArrayList<PaymentCheck>();
	private List<RequestCourse>  requestCourses = new ArrayList<RequestCourse>();
	private List<Report> reports = new ArrayList<Report>();
	private List<CourseCreator> courseCreators = new ArrayList<CourseCreator>();
	private List<Comment> comments = new ArrayList<Comment>();
	private List<User> users = new ArrayList<User>();

	public User() {
	}

	public User(Account account, User user, String userName, String verifyStatus, String imgPath) {
		this.setAccount(account);
		this.setUser(user);
		this.setUserName(userName);
		this.setVerifyStatus(verifyStatus);
		this.setImgPath(imgPath);
	}

	public User(Account account, User user, String userName, String verifyStatus, String imgPath, List<Bookmark> bookmarks,
			List<RequestVerifyDetail> requestverifydetails, List<PostLike> postlikes, List<CommentLike> commentlikes, List<Post> posts, List<PaymentCheck> paymentchecks, List<RequestCourse> requestcourses,
			List<Report> reports, List<CourseCreator> coursecreators, List<Comment> comments, List<User> users) {
		this.setAccount(account);
		this.setUser(user);
		this.setUserName(userName);
		this.setVerifyStatus(verifyStatus);
		this.setImgPath(imgPath);
		this.setBookmarks(bookmarks);
		this.setRequestVerifyDetails(requestverifydetails);
		this.setPostLikes(postlikes);
		this.setCommentLikes(commentlikes);
		this.setPosts(posts);
		this.setPaymentChecks(paymentchecks);
		this.setRequestCourses(requestcourses);
		this.setReports(reports);
		this.setCourseCreators(coursecreators);
		this.setComments(comments);
		this.setUsers(users);
	}

	public int getUserId() {
		return userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public Account getAccount() {
		return account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getVerifyStatus() {
		return verifyStatus;
	}

	public void setVerifyStatus(String verifyStatus) {
		this.verifyStatus = verifyStatus;
	}

	public String getImgPath() {
		return imgPath;
	}

	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}

	public List<Bookmark> getBookmarks() {
		return bookmarks;
	}

	public void setBookmarks(List<Bookmark> bookmarks) {
		this.bookmarks = bookmarks;
	}

	public List<RequestVerifyDetail> getRequestVerifyDetails() {
		return requestVerifyDetails;
	}

	public void setRequestVerifyDetails(List<RequestVerifyDetail> requestVerifyDetails) {
		this.requestVerifyDetails = requestVerifyDetails;
	}

	public List<PostLike> getPostLikes() {
		return postLikes;
	}

	public void setPostLikes(List<PostLike> postLikes) {
		this.postLikes = postLikes;
	}

	public List<CommentLike> getCommentLikes() {
		return commentLikes;
	}

	public void setCommentLikes(List<CommentLike> commentLikes) {
		this.commentLikes = commentLikes;
	}

	public List<Post> getPosts() {
		return posts;
	}

	public void setPosts(List<Post> posts) {
		this.posts = posts;
	}

	public List<PaymentCheck> getPaymentChecks() {
		return paymentChecks;
	}

	public void setPaymentChecks(List<PaymentCheck> paymentChecks) {
		this.paymentChecks = paymentChecks;
	}

	public List<RequestCourse> getRequestCourses() {
		return requestCourses;
	}

	public void setRequestCourses(List<RequestCourse> requestCourses) {
		this.requestCourses = requestCourses;
	}

	public List<Report> getReports() {
		return reports;
	}

	public void setReports(List<Report> reports) {
		this.reports = reports;
	}

	public List<CourseCreator> getCourseCreators() {
		return courseCreators;
	}

	public void setCourseCreators(List<CourseCreator> courseCreators) {
		this.courseCreators = courseCreators;
	}

	public List<Comment> getComments() {
		return comments;
	}

	public void setComments(List<Comment> comments) {
		this.comments = comments;
	}

	public List<User> getUsers() {
		return users;
	}

	public void setUsers(List<User> users) {
		this.users = users;
	}

	
}
