package eng.cpe.se.project.model;

import javax.validation.constraints.Digits;
import javax.validation.constraints.Email;
import javax.validation.constraints.Max;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.fasterxml.jackson.annotation.JsonIgnore;

import eng.cpe.se.project.security.validation.PasswordMatches;



// Generated Mar 5, 2023, 12:22:12 AM by Hibernate Tools 5.6.3.Final

/**
 * Account generated by hbm2java
 */
@PasswordMatches
public class Account implements java.io.Serializable {

	private int accountId;
	@NotNull(message = "Email cannot be null")
	@NotBlank(message = "Password may not be blank")
	@NotEmpty(message = "Password may not be empty")
	@Email
	private String email;
	@NotNull(message = "Password cannot be null")
	@NotBlank(message = "Password may not be blank")
	@NotEmpty(message = "Password may not be empty")
	@Size(min = 2, max = 20, message = "Password must be between 2 and 20 characters long")
	private String password;
	@NotNull(message = "Password cannot be null")
	@NotBlank(message = "Password may not be blank")
	@NotEmpty(message = "Password may not be empty")
	@Size(min = 2, max = 20, message = "Password must be between 2 and 20 characters long")
	private String matchingPassword;
	@NotNull(message = "Title cannot be null")
	@NotBlank(message = "Password may not be blank")
	@NotEmpty(message = "Password may not be empty")
	@Size(min = 2, max = 10, message = "Password must be between 2 and 10 characters long")
	private String title;
	@NotNull(message = "FirstName cannot be null")
	@NotBlank(message = "Password may not be blank")
	@NotEmpty(message = "Password may not be empty")
	@Size(min = 2, max = 50, message = "Password must be between 2 and 50 characters long")
	private String firstName;
	@NotNull(message = "LastName cannot be null")
	@NotBlank(message = "Password may not be blank")
	@NotEmpty(message = "Password may not be empty")
	@Size(min = 2, max = 50, message = "Password must be between 2 and 50 characters long")
	private String lastName;
	@NotNull(message = "PhoneNumber cannot be null")
	@Digits(message="Number should contain 10 digits.", fraction = 0, integer = 10)
	private String phoneNumber;
	private String role;
	@JsonIgnore
	private Staff staff;
	@JsonIgnore
	private User user;

	public Account() {
	}

	public Account(String email, String password,String matchingPassword, String title, String firstName, String lastName, String phoneNumber, String role) {
		this.email = email;
		this.password = password;
		this.matchingPassword = matchingPassword;
		this.title = title;
		this.firstName = firstName;
		this.lastName = lastName;
		this.phoneNumber = phoneNumber;
		this.role = role;
	}

	public Account(String email, String password,String matchingPassword, String title, String firstName, String lastName, String phoneNumber,String role,
			Staff staff, User user) {
		this.email = email;
		this.password = password;
		this.matchingPassword = matchingPassword;
		this.title = title;
		this.firstName = firstName;
		this.lastName = lastName;
		this.phoneNumber = phoneNumber;
		this.role = role;
		this.staff = staff;
		this.user = user;
	}
	
	public void clone(Account otherAccount) {
		this.email = otherAccount.email;
		this.password = otherAccount.password;
		this.title = otherAccount.title;
		this.firstName = otherAccount.firstName;
		this.lastName = otherAccount.lastName;
		this.phoneNumber = otherAccount.phoneNumber;
		this.role = otherAccount.role;
	}

	public int getAccountId() {
		return this.accountId;
	}

	public void setAccountId(int accountId) {
		this.accountId = accountId;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public Staff getStaff() {
		return this.staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getMatchingPassword() {
		return matchingPassword;
	}

	public void setMatchingPassword(String matchingPassword) {
		this.matchingPassword = matchingPassword;
	}

	public String getRole() {
		return role;
	}

	public void setRole(String role) {
		this.role = role;
	}
	
	
}
