package eng.cpe.se.project.model;
// Generated Mar 7, 2023, 11:29:50 PM by Hibernate Tools 5.6.3.Final

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Bookmark generated by hbm2java
 */
public class Bookmark implements java.io.Serializable {

	private Integer bookmarkId;
	@JsonIgnore
	private Post post;
	@JsonIgnore
	private User user;

	public Bookmark() {
	}

	public Bookmark(Post post, User user) {
		this.post = post;
		this.user = user;
	}

	public Integer getBookmarkId() {
		return this.bookmarkId;
	}

	public void setBookmarkId(Integer bookmarkId) {
		this.bookmarkId = bookmarkId;
	}

	public Post getPost() {
		return this.post;
	}

	public void setPost(Post post) {
		this.post = post;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
