package eng.cpe.se.project.model;
// Generated Mar 5, 2023, 12:22:12 AM by Hibernate Tools 5.6.3.Final

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Bookmark generated by hbm2java
 */
public class Bookmark implements java.io.Serializable {

	private int bookmarkId;
	@JsonIgnore
	@NotNull(message = "post cannot be null")
	private Post post;
	@JsonIgnore
	@NotNull(message = "user cannot be null")
	private User user;

	public Bookmark() {
	}

	public Bookmark(Post post, User user) {
		this.post = post;
		this.user = user;
	}
	

	public int getBookmarkId() {
		return this.bookmarkId;
	}

	public void setBookmarkId(int bookmarkId) {
		this.bookmarkId = bookmarkId;
	}

	public Post getPost() {
		return this.post;
	}

	public void setPost(Post post) {
		this.post = post;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
