package eng.cpe.se.project.model;
// Generated Mar 1, 2023, 12:55:07 AM by Hibernate Tools 5.6.3.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Comment generated by hbm2java
 */
public class Comment implements java.io.Serializable {

	private int commentId;
	@JsonIgnore
	private Post post;
	@JsonIgnore
	private User user;
	private String commentDetail;
	@JsonIgnore
	private List<ImgComment> imgComments = new ArrayList<ImgComment>();
	@JsonIgnore
	private List<Report> reports = new ArrayList<Report>();
	@JsonIgnore
	private List<CommentLike> commentLikes = new ArrayList<CommentLike>();

	public Comment() {
	}

	public Comment(Post post, User user, String commentDetail) {
		this.setPost(post);
		this.setUser(user);
		this.setCommentDetail(commentDetail);
	}

	public Comment(Post post, User user, String commentDetail, List<ImgComment> imgcomments, List<Report> reports, List<CommentLike> commentlikes) {
		this.setPost(post);
		this.setUser(user);
		this.setCommentDetail(commentDetail);
		this.setImgComments(imgcomments);
		this.setReports(reports);
		this.setCommentLikes(commentlikes);
	}

	public int getCommentId() {
		return commentId;
	}

	public void setCommentId(int commentId) {
		this.commentId = commentId;
	}

	public Post getPost() {
		return post;
	}

	public void setPost(Post post) {
		this.post = post;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getCommentDetail() {
		return commentDetail;
	}

	public void setCommentDetail(String commentDetail) {
		this.commentDetail = commentDetail;
	}

	public List<ImgComment> getImgComments() {
		return imgComments;
	}

	public void setImgComments(List<ImgComment> imgComments) {
		this.imgComments = imgComments;
	}

	public List<Report> getReports() {
		return reports;
	}

	public void setReports(List<Report> reports) {
		this.reports = reports;
	}

	public List<CommentLike> getCommentLikes() {
		return commentLikes;
	}

	public void setCommentLikes(List<CommentLike> commentLikes) {
		this.commentLikes = commentLikes;
	}


}
