package eng.cpe.se.project.model;
// Generated Mar 7, 2023, 11:29:50 PM by Hibernate Tools 5.6.3.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Contenttype generated by hbm2java
 */
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class ContentType implements java.io.Serializable {

	private Integer contentTypeId;
	private String typeName;
	@JsonIgnore
	private List<Course> courses = new ArrayList<Course>();
	@JsonIgnore
	private List<Post> posts = new ArrayList<Post>();

	public ContentType() {
	}

	public ContentType(String typeName) {
		this.typeName = typeName;
	}

	public ContentType(Integer contentTypeId, String typeName, List<Course> courses, List<Post> posts) {
		super();
		this.contentTypeId = contentTypeId;
		this.typeName = typeName;
		this.courses = courses;
		this.posts = posts;
	}

	public Integer getContentTypeId() {
		return contentTypeId;
	}

	public void setContentTypeId(Integer contentTypeId) {
		this.contentTypeId = contentTypeId;
	}

	public String getTypeName() {
		return typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	public List<Course> getCourses() {
		return courses;
	}

	public void setCourses(List<Course> courses) {
		this.courses = courses;
	}

	public List<Post> getPosts() {
		return posts;
	}

	public void setPosts(List<Post> posts) {
		this.posts = posts;
	}

}
