package eng.cpe.se.project.model;
// Generated Mar 7, 2023, 11:29:50 PM by Hibernate Tools 5.6.3.Final

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Follower generated by hbm2java
 */
public class Follower implements java.io.Serializable {

	private Integer followerId;
	@JsonIgnore
	private User userByFollowBy;
	@JsonIgnore
	private User userByFollowTo;

	public Follower() {
	}

	public Follower(User userByFollowBy, User userByFollowTo) {
		this.userByFollowBy = userByFollowBy;
		this.userByFollowTo = userByFollowTo;
	}

	public Integer getFollowerId() {
		return this.followerId;
	}

	public void setFollowerId(Integer followerId) {
		this.followerId = followerId;
	}

	public User getUserByFollowBy() {
		return this.userByFollowBy;
	}

	public void setUserByFollowBy(User userByFollowBy) {
		this.userByFollowBy = userByFollowBy;
	}

	public User getUserByFollowTo() {
		return this.userByFollowTo;
	}

	public void setUserByFollowTo(User userByFollowTo) {
		this.userByFollowTo = userByFollowTo;
	}

}
