package eng.cpe.se.project.model;
// Generated Mar 7, 2023, 11:29:50 PM by Hibernate Tools 5.6.3.Final

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Imgcomment generated by hbm2java
 */
public class ImgComment implements java.io.Serializable {

	private Integer imgCommentId;
	@JsonIgnore
	private Comment comment;
	private String imgPath;

	public ImgComment() {
	}

	public ImgComment(Comment comment, String imgPath) {
		this.comment = comment;
		this.imgPath = imgPath;
	}

	public Integer getImgCommentId() {
		return this.imgCommentId;
	}

	public void setImgCommentId(Integer imgCommentId) {
		this.imgCommentId = imgCommentId;
	}

	public Comment getComment() {
		return this.comment;
	}

	public void setComment(Comment comment) {
		this.comment = comment;
	}

	public String getImgPath() {
		return this.imgPath;
	}

	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}

}
