package eng.cpe.se.project.model;
// Generated Mar 5, 2023, 12:22:12 AM by Hibernate Tools 5.6.3.Final

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Imgcourse generated by hbm2java
 */
public class ImgCourse implements java.io.Serializable {

	private int imgCourseId;
	@JsonIgnore
	private Course course;
	private String imgPath;

	public ImgCourse() {
	}

	public ImgCourse(Course course, String imgPath) {
		this.course = course;
		this.imgPath = imgPath;
	}
	
	public void clone(ImgCourse other) {
		this.imgPath = other.imgPath;
	}

	public int getImgCourseId() {
		return this.imgCourseId;
	}

	public void setImgCourseId(int imgCourseId) {
		this.imgCourseId = imgCourseId;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public String getImgPath() {
		return this.imgPath;
	}

	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}

}
