package eng.cpe.se.project.model;
// Generated Mar 7, 2023, 11:29:50 PM by Hibernate Tools 5.6.3.Final

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Imgcourse generated by hbm2java
 */
public class ImgCourse implements java.io.Serializable {

	private Integer imgCourseId;
	@JsonIgnore
	private Course course;
	private String imgPath;

	public ImgCourse() {
	}

	public ImgCourse(Course course, String imgPath) {
		this.course = course;
		this.imgPath = imgPath;
	}

	public Integer getImgCourseId() {
		return this.imgCourseId;
	}

	public void setImgCourseId(Integer imgCourseId) {
		this.imgCourseId = imgCourseId;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public String getImgPath() {
		return this.imgPath;
	}

	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}

}
