package eng.cpe.se.project.model;
// Generated Mar 7, 2023, 11:29:50 PM by Hibernate Tools 5.6.3.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Joincourse generated by hbm2java
 */
public class JoinCourse implements java.io.Serializable {

	private Integer joinCourseId;
	@JsonIgnore
	private Course course;
	@JsonIgnore
	private List<PaymentCheck> paymentChecks = new ArrayList<PaymentCheck>();

	public JoinCourse() {
	}

	public JoinCourse(Course course) {
		this.course = course;
	}

	public JoinCourse(Integer joinCourseId, Course course, List<PaymentCheck> paymentChecks) {
		super();
		this.joinCourseId = joinCourseId;
		this.course = course;
		this.paymentChecks = paymentChecks;
	}

	public Integer getJoinCourseId() {
		return joinCourseId;
	}

	public void setJoinCourseId(Integer joinCourseId) {
		this.joinCourseId = joinCourseId;
	}

	public Course getCourse() {
		return course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public List<PaymentCheck> getPaymentChecks() {
		return paymentChecks;
	}

	public void setPaymentChecks(List<PaymentCheck> paymentChecks) {
		this.paymentChecks = paymentChecks;
	}

}
