package eng.cpe.se.project.model;

import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;

// Generated Mar 5, 2023, 12:22:12 AM by Hibernate Tools 5.6.3.Final

/**
 * Joincourse generated by hbm2java
 */
public class JoinCourse implements java.io.Serializable {

	private int joinCourseId;
	@JsonIgnore
	private Course course;
	@JsonIgnore
	private List<PaymentCheck> paymentChecks = new ArrayList<PaymentCheck>();

	public JoinCourse() {
	}

	public JoinCourse(Course course, List<PaymentCheck> paymentChecks) {
		this.course = course;
		this.paymentChecks = paymentChecks;
	}

	public int getJoinCourseId() {
		return joinCourseId;
	}

	public void setJoinCourseId(int joinCourseId) {
		this.joinCourseId = joinCourseId;
	}

	public Course getCourse() {
		return course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public List<PaymentCheck> getPaymentChecks() {
		return paymentChecks;
	}

	public void setPaymentChecks(List<PaymentCheck> paymentChecks) {
		this.paymentChecks = paymentChecks;
	}


}
