package eng.cpe.se.project.model;
// Generated Mar 7, 2023, 11:29:50 PM by Hibernate Tools 5.6.3.Final

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Paymentcheck generated by hbm2java
 */
public class PaymentCheck implements java.io.Serializable {

	private Integer paymentCheckId;
	@JsonIgnore
	private JoinCourse joinCourse;
	@JsonIgnore
	private User user;
	private String imgPath;

	public PaymentCheck() {
	}

	public PaymentCheck(JoinCourse joincourse, User user, String imgPath) {
		this.joinCourse = joincourse;
		this.user = user;
		this.imgPath = imgPath;
	}

	public Integer getPaymentCheckId() {
		return paymentCheckId;
	}

	public void setPaymentCheckId(Integer paymentCheckId) {
		this.paymentCheckId = paymentCheckId;
	}

	public JoinCourse getJoinCourse() {
		return joinCourse;
	}

	public void setJoinCourse(JoinCourse joinCourse) {
		this.joinCourse = joinCourse;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getImgPath() {
		return imgPath;
	}

	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}


}
