package eng.cpe.se.project.model;
// Generated Mar 5, 2023, 12:22:12 AM by Hibernate Tools 5.6.3.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Post generated by hbm2java
 */
public class Post implements java.io.Serializable {

	private int postId;
	@JsonIgnore
	private ContentType contentType;
	@JsonIgnore
	private User user;
	private String postTopic;
	private String postDetail;
	private String reportStatus;
	private Date createDate;
	@JsonIgnore
	private List<Bookmark> bookmarks = new ArrayList<Bookmark>();
	@JsonIgnore
	private List<Report> reports = new ArrayList<Report>();
	@JsonIgnore
	private List<ImgPost> imgPosts = new ArrayList<ImgPost>();
	@JsonIgnore
	private List<Comment> comments = new ArrayList<Comment>();
	@JsonIgnore
	private List<LikePost> likePosts = new ArrayList<LikePost>();

	public Post() {
	}

	public Post(ContentType contenttype, User user, String postTopic, String postDetail,String reportStatus, Date createDate) {
		this.contentType = contenttype;
		this.user = user;
		this.postTopic = postTopic;
		this.postDetail = postDetail;
		this.setReportStatus(reportStatus);
		this.createDate = createDate;
	}

	public Post(ContentType contenttype, User user, String postTopic, String postDetail, String reportStatus, Date createDate,
			List<Bookmark> bookmarks, List<Report> reports, List<ImgPost> imgposts, List<Comment> comments, List<LikePost> likeposts) {
		this.contentType = contenttype;
		this.user = user;
		this.postTopic = postTopic;
		this.postDetail = postDetail;
		this.setReportStatus(reportStatus);
		this.createDate = createDate;
		this.bookmarks = bookmarks;
		this.reports = reports;
		this.imgPosts = imgposts;
		this.comments = comments;
		this.likePosts = likeposts;
	}
	
	public void clone(Post other) {
		this.postTopic = other.postTopic;
		this.postDetail = other.postDetail;
		this.reportStatus = reportStatus;
		this.createDate = other.createDate;
	}

	public int getPostId() {
		return postId;
	}

	public void setPostId(int postId) {
		this.postId = postId;
	}

	public ContentType getContentType() {
		return contentType;
	}

	public void setContentType(ContentType contentType) {
		this.contentType = contentType;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getPostTopic() {
		return postTopic;
	}

	public void setPostTopic(String postTopic) {
		this.postTopic = postTopic;
	}

	public String getPostDetail() {
		return postDetail;
	}

	public void setPostDetail(String postDetail) {
		this.postDetail = postDetail;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public List<Bookmark> getBookmarks() {
		return bookmarks;
	}

	public void setBookmarks(List<Bookmark> bookmarks) {
		this.bookmarks = bookmarks;
	}

	public List<Report> getReports() {
		return reports;
	}

	public void setReports(List<Report> reports) {
		this.reports = reports;
	}

	public List<ImgPost> getImgPosts() {
		return imgPosts;
	}

	public void setImgPosts(List<ImgPost> imgPosts) {
		this.imgPosts = imgPosts;
	}

	public List<Comment> getComments() {
		return comments;
	}

	public void setComments(List<Comment> comments) {
		this.comments = comments;
	}

	public List<LikePost> getLikePosts() {
		return likePosts;
	}

	public void setLikePosts(List<LikePost> likePosts) {
		this.likePosts = likePosts;
	}

	public String getReportStatus() {
		return reportStatus;
	}

	public void setReportStatus(String reportStatus) {
		this.reportStatus = reportStatus;
	}


}
