package eng.cpe.se.project.model;
// Generated Mar 7, 2023, 11:29:50 PM by Hibernate Tools 5.6.3.Final

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Report generated by hbm2java
 */
public class Report implements java.io.Serializable {

	private Integer reportId;
	@JsonIgnore
	private Comment comment;
	@JsonIgnore
	private Course course;
	@JsonIgnore
	private Post post;
	@JsonIgnore
	private ReportType reportType;
	@JsonIgnore
	private User user;
	private String reportDetail;
	private String status;

	public Report() {
	}

	public Report(Integer reportId, Comment comment, Course course, Post post, ReportType reportType, User user,
			String reportDetail, String status) {
		super();
		this.reportId = reportId;
		this.comment = comment;
		this.course = course;
		this.post = post;
		this.reportType = reportType;
		this.user = user;
		this.reportDetail = reportDetail;
		this.status = status;
	}

	public Integer getReportId() {
		return reportId;
	}

	public void setReportId(Integer reportId) {
		this.reportId = reportId;
	}

	public Comment getComment() {
		return comment;
	}

	public void setComment(Comment comment) {
		this.comment = comment;
	}

	public Course getCourse() {
		return course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public Post getPost() {
		return post;
	}

	public void setPost(Post post) {
		this.post = post;
	}

	public ReportType getReportType() {
		return reportType;
	}

	public void setReportType(ReportType reportType) {
		this.reportType = reportType;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getReportDetail() {
		return reportDetail;
	}

	public void setReportDetail(String reportDetail) {
		this.reportDetail = reportDetail;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
