package eng.cpe.se.project.model;
// Generated Mar 7, 2023, 11:29:50 PM by Hibernate Tools 5.6.3.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Reporttype generated by hbm2java
 */
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class ReportType implements java.io.Serializable {

	private Integer reportTypeId;
	private String typeName;
	@JsonIgnore
	private List<Report> reports = new ArrayList<Report>();

	public ReportType() {
	}

	public ReportType(String typeName) {
		this.typeName = typeName;
	}

	public ReportType(Integer reportTypeId, String typeName, List<Report> reports) {
		super();
		this.reportTypeId = reportTypeId;
		this.typeName = typeName;
		this.reports = reports;
	}

	public Integer getReportTypeId() {
		return reportTypeId;
	}

	public void setReportTypeId(Integer reportTypeId) {
		this.reportTypeId = reportTypeId;
	}

	public String getTypeName() {
		return typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	public List<Report> getReports() {
		return reports;
	}

	public void setReports(List<Report> reports) {
		this.reports = reports;
	}

}
