package eng.cpe.se.project.model;
// Generated Mar 1, 2023, 12:55:07 AM by Hibernate Tools 5.6.3.Final

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Report generated by hbm2java
 */
public class Report implements java.io.Serializable {

	private int reportId;
	@JsonIgnore
	private Comment comment;
	@JsonIgnore
	private Course course;
	@JsonIgnore
	private Post post;
	@JsonIgnore
	private User user;
	private String reportDetail;

	public Report() {
	}

	public Report(User user) {
		this.user = user;
	}

	public Report(Comment comment, Course course, Post post, User user) {
		this.comment = comment;
		this.course = course;
		this.post = post;
		this.user = user;
	}

	public int getReportId() {
		return this.reportId;
	}

	public void setReportId(int reportId) {
		this.reportId = reportId;
	}

	public Comment getComment() {
		return this.comment;
	}

	public void setComment(Comment comment) {
		this.comment = comment;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public Post getPost() {
		return this.post;
	}

	public void setPost(Post post) {
		this.post = post;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getReportDetail() {
		return reportDetail;
	}

	public void setReportDetail(String reportDetail) {
		this.reportDetail = reportDetail;
	}

}
