package eng.cpe.se.project.model;
// Generated Mar 7, 2023, 11:29:50 PM by Hibernate Tools 5.6.3.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Requestverify generated by hbm2java
 */
public class RequestVerify implements java.io.Serializable {

	private Integer requestVerifyId;
	@JsonIgnore
	private User userByUserId;
	@JsonIgnore
	private User userByStaffId;
	private String verifyHeader;
	private String verifyDetail;
	private String approveStatus;
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
	private Date dateApprove;
	@JsonIgnore
	private List<ImgVerify> imgVerifies = new ArrayList<ImgVerify>();

	public RequestVerify() {
	}

	public RequestVerify(Integer requestVerifyId, User userByUserId, User userByStaffId, String verifyHeader,
			String verifyDetail, String approveStatus, Date dateApprove, List<ImgVerify> imgVerifies) {
		super();
		this.requestVerifyId = requestVerifyId;
		this.userByUserId = userByUserId;
		this.userByStaffId = userByStaffId;
		this.verifyHeader = verifyHeader;
		this.verifyDetail = verifyDetail;
		this.approveStatus = approveStatus;
		this.dateApprove = dateApprove;
		this.imgVerifies = imgVerifies;
	}
	
	public void clone(RequestVerify other) {
		this.verifyHeader = other.verifyHeader;
		this.verifyDetail = other.verifyDetail;
		this.approveStatus = other.approveStatus;
	}

	public Integer getRequestVerifyId() {
		return requestVerifyId;
	}

	public void setRequestVerifyId(Integer requestVerifyId) {
		this.requestVerifyId = requestVerifyId;
	}

	public User getUserByUserId() {
		return userByUserId;
	}

	public void setUserByUserId(User userByUserId) {
		this.userByUserId = userByUserId;
	}

	public User getUserByStaffId() {
		return userByStaffId;
	}

	public void setUserByStaffId(User userByStaffId) {
		this.userByStaffId = userByStaffId;
	}

	public String getVerifyHeader() {
		return verifyHeader;
	}

	public void setVerifyHeader(String verifyHeader) {
		this.verifyHeader = verifyHeader;
	}

	public String getVerifyDetail() {
		return verifyDetail;
	}

	public void setVerifyDetail(String verifyDetail) {
		this.verifyDetail = verifyDetail;
	}

	public String getApproveStatus() {
		return approveStatus;
	}

	public void setApproveStatus(String approveStatus) {
		this.approveStatus = approveStatus;
	}

	public Date getDateApprove() {
		return dateApprove;
	}

	public void setDateApprove(Date dateApprove) {
		this.dateApprove = dateApprove;
	}

	public List<ImgVerify> getImgVerifies() {
		return imgVerifies;
	}

	public void setImgVerifies(List<ImgVerify> imgVerifies) {
		this.imgVerifies = imgVerifies;
	}


}
