package eng.cpe.se.project.model;
// Generated Mar 5, 2023, 12:22:12 AM by Hibernate Tools 5.6.3.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Staff generated by hbm2java
 */
public class Staff implements java.io.Serializable {

	private int staffId;
	@JsonIgnore
	private Account account;
	private String position;
	@JsonIgnore
	private List<RequestVerify> requestVerifies = new ArrayList<RequestVerify>();

	public Staff() {
	}

	public Staff(Account account, String position) {
		this.account = account;
		this.position = position;
	}

	public Staff(Account account, String position, List<RequestVerify> requestverifies) {
		this.account = account;
		this.position = position;
		this.requestVerifies = requestverifies;
	}
	
	public void clone(Staff other) {
		this.position = other.position;
	}

	public int getStaffId() {
		return staffId;
	}

	public void setStaffId(int staffId) {
		this.staffId = staffId;
	}

	public Account getAccount() {
		return account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public String getPosition() {
		return position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public List<RequestVerify> getRequestVerifies() {
		return requestVerifies;
	}

	public void setRequestVerifies(List<RequestVerify> requestVerifies) {
		this.requestVerifies = requestVerifies;
	}

	

}
