package eng.cpe.se.project.model;
// Generated Mar 5, 2023, 12:22:12 AM by Hibernate Tools 5.6.3.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private int userId;
	@JsonIgnore
	private Account account;
	private String username;
	private String imgPath;
	private String backgroundPath;
	private String verifyStatus;
	private String type;
	@JsonIgnore
	private List<Comment> comments = new ArrayList<Comment>();
	@JsonIgnore
	private List<LikeComment> likeComments = new ArrayList<LikeComment>();
	@JsonIgnore
	private List<Follower> followersForFollowTo = new ArrayList<Follower>();
	@JsonIgnore
	private List<Follower> followersForFollowBy = new ArrayList<Follower>();
	@JsonIgnore
	private List<PaymentCheck> paymentChecks = new ArrayList<PaymentCheck>();
	@JsonIgnore
	private List<JoinCourse> joinCourses = new ArrayList<JoinCourse>();
	@JsonIgnore
	private List<Post> posts = new ArrayList<Post>();
	@JsonIgnore
	private List<RequestCourse> requestCourses = new ArrayList<RequestCourse>();
	@JsonIgnore
	private List<LikePost> likePosts = new ArrayList<LikePost>();
	@JsonIgnore
	private List<Course> courses = new ArrayList<Course>();
	@JsonIgnore
	private List<Report> reports = new ArrayList<Report>();
	@JsonIgnore
	private List<Bookmark> bookmarks = new ArrayList<Bookmark>();
	@JsonIgnore
	private List<RequestVerify> requestVerifies = new ArrayList<RequestVerify>();

	public User() {
	}

	public User(Account account, String username, String imgPath, String backgroundPath, String verifyStatus,
			String type) {
		this.account = account;
		this.username = username;
		this.imgPath = imgPath;
		this.backgroundPath = backgroundPath;
		this.verifyStatus = verifyStatus;
		this.type = type;
	}

	public User(Account account, String username, String imgPath, String backgroundPath, String verifyStatus,
			String type, List<Comment> comments, List<LikeComment> likecomments, List<Follower> followersForFollowTo, List<Follower> followersForFollowBy,
			List<PaymentCheck> paymentChecks, List<JoinCourse> joincourses, List<Post> posts, List<RequestCourse> requestCourses, List<LikePost> likeposts, 
			List<Course> courses, List<Report> reports, List<Bookmark> bookmarks, List<RequestVerify> requestverifies) {
		this.account = account;
		this.username = username;
		this.imgPath = imgPath;
		this.backgroundPath = backgroundPath;
		this.verifyStatus = verifyStatus;
		this.type = type;
		this.comments = comments;
		this.likeComments = likecomments;
		this.followersForFollowTo = followersForFollowTo;
		this.followersForFollowBy = followersForFollowBy;
		this.paymentChecks = paymentChecks;
		this.joinCourses = joincourses;
		this.posts = posts;
		this.requestCourses = requestCourses;
		this.likePosts = likeposts;
		this.courses = courses;
		this.reports = reports;
		this.bookmarks = bookmarks;
		this.requestVerifies = requestverifies;
	}
	
	public void clone(User other) {
		this.username = other.username;
		this.imgPath = other.imgPath;
		this.backgroundPath = other.backgroundPath;
		this.verifyStatus = other.verifyStatus;
		this.type = other.type;
	}

	public int getUserId() {
		return userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public Account getAccount() {
		return account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getImgPath() {
		return imgPath;
	}

	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}

	public String getBackgroundPath() {
		return backgroundPath;
	}

	public void setBackgroundPath(String backgroundPath) {
		this.backgroundPath = backgroundPath;
	}

	public String getVerifyStatus() {
		return verifyStatus;
	}

	public void setVerifyStatus(String verifyStatus) {
		this.verifyStatus = verifyStatus;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public List<Comment> getComments() {
		return comments;
	}

	public void setComments(List<Comment> comments) {
		this.comments = comments;
	}

	public List<LikeComment> getLikeComments() {
		return likeComments;
	}

	public void setLikeComments(List<LikeComment> likeComments) {
		this.likeComments = likeComments;
	}

	public List<JoinCourse> getJoinCourses() {
		return joinCourses;
	}

	public void setJoinCourses(List<JoinCourse> joinCourses) {
		this.joinCourses = joinCourses;
	}

	public List<Post> getPosts() {
		return posts;
	}

	public void setPosts(List<Post> posts) {
		this.posts = posts;
	}

	public List<LikePost> getLikePosts() {
		return likePosts;
	}

	public void setLikePosts(List<LikePost> likePosts) {
		this.likePosts = likePosts;
	}

	public List<Course> getCourses() {
		return courses;
	}

	public void setCourses(List<Course> courses) {
		this.courses = courses;
	}

	public List<Report> getReports() {
		return reports;
	}

	public void setReports(List<Report> reports) {
		this.reports = reports;
	}

	public List<Bookmark> getBookmarks() {
		return bookmarks;
	}

	public void setBookmarks(List<Bookmark> bookmarks) {
		this.bookmarks = bookmarks;
	}

	public List<RequestVerify> getRequestVerifies() {
		return requestVerifies;
	}

	public void setRequestVerifies(List<RequestVerify> requestVerifies) {
		this.requestVerifies = requestVerifies;
	}

	public List<RequestCourse> getRequestCourses() {
		return requestCourses;
	}

	public void setRequestCourses(List<RequestCourse> requestCourses) {
		this.requestCourses = requestCourses;
	}

	public List<Follower> getFollowersForFollowTo() {
		return followersForFollowTo;
	}

	public void setFollowersForFollowTo(List<Follower> followersForFollowTo) {
		this.followersForFollowTo = followersForFollowTo;
	}

	public List<Follower> getFollowersForFollowBy() {
		return followersForFollowBy;
	}

	public void setFollowersForFollowBy(List<Follower> followersForFollowBy) {
		this.followersForFollowBy = followersForFollowBy;
	}

	public List<PaymentCheck> getPaymentChecks() {
		return paymentChecks;
	}

	public void setPaymentChecks(List<PaymentCheck> paymentChecks) {
		this.paymentChecks = paymentChecks;
	}


}
