package eng.cpe.se.project.model;
// Generated Mar 1, 2023, 12:55:07 AM by Hibernate Tools 5.6.3.Final

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Approvewithdrawdetail generated by hbm2java
 */
public class ApproveWithdrawDetail implements java.io.Serializable {

	private int approveWithdrawDetailId;
	@JsonIgnore
	private ApproveWithdraw approveWithdraw;
	@JsonIgnore
	private WithdrawReport withdrawReport;

	public ApproveWithdrawDetail() {
	}

	public ApproveWithdrawDetail(ApproveWithdraw approvewithdraw, WithdrawReport withdrawreport) {
		this.approveWithdraw = approvewithdraw;
		this.withdrawReport = withdrawreport;
	}

	public int getApproveWithdrawDetailId() {
		return approveWithdrawDetailId;
	}

	public void setApproveWithdrawDetailId(int approveWithdrawDetailId) {
		this.approveWithdrawDetailId = approveWithdrawDetailId;
	}

	public ApproveWithdraw getApproveWithdraw() {
		return approveWithdraw;
	}

	public void setApproveWithdraw(ApproveWithdraw approveWithdraw) {
		this.approveWithdraw = approveWithdraw;
	}

	public WithdrawReport getWithdrawReport() {
		return withdrawReport;
	}

	public void setWithdrawReport(WithdrawReport withdrawReport) {
		this.withdrawReport = withdrawReport;
	}
	

}
