package eng.cpe.se.project.model;
// Generated Mar 1, 2023, 12:55:07 AM by Hibernate Tools 5.6.3.Final

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Paymentcheck generated by hbm2java
 */
public class PaymentCheck implements java.io.Serializable {

	private int paymentId;
	@JsonIgnore
	private JoinCourse joinCourse;
	@JsonIgnore
	private Staff staff;
	@JsonIgnore
	private User user;
	private String status;
	private String imgPath;

	public PaymentCheck() {
	}

	public PaymentCheck(JoinCourse joincourse, Staff staff, User user, String status, String imgPath) {
		this.joinCourse = joincourse;
		this.staff = staff;
		this.user = user;
		this.status = status;
		this.imgPath = imgPath;
	}

	public int getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(int paymentId) {
		this.paymentId = paymentId;
	}

	public JoinCourse getJoincourse() {
		return this.joinCourse;
	}

	public void setJoincourse(JoinCourse joincourse) {
		this.joinCourse = joincourse;
	}

	public Staff getStaff() {
		return this.staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getImgPath() {
		return this.imgPath;
	}

	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}

}
