package eng.cpe.se.project.model;
// Generated Feb 24, 2023, 1:08:39 AM by Hibernate Tools 5.6.3.Final

/**
 * Paymentcheck generated by hbm2java
 */
public class PaymentCheck implements java.io.Serializable {

	private int paymentId;
	private JoinCourse joinCourse;
	private Staff staff;
	private User user;
	private String status;
	private String imgPath;

	public PaymentCheck() {
	}

	public PaymentCheck(int paymentId, JoinCourse joincourse, Staff staff, User user, String status, String imgPath) {
		this.paymentId = paymentId;
		this.setJoinCourse(joincourse);
		this.staff = staff;
		this.user = user;
		this.status = status;
		this.imgPath = imgPath;
	}

	public int getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(int paymentId) {
		this.paymentId = paymentId;
	}

	public Staff getStaff() {
		return this.staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getImgPath() {
		return this.imgPath;
	}

	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}

	public JoinCourse getJoinCourse() {
		return joinCourse;
	}

	public void setJoinCourse(JoinCourse joinCourse) {
		this.joinCourse = joinCourse;
	}

}
