package eng.cpe.se.project.model;
// Generated Mar 1, 2023, 12:55:07 AM by Hibernate Tools 5.6.3.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Post generated by hbm2java
 */
public class Post implements java.io.Serializable {

	private int postId;
	@JsonIgnore
	private Type type;
	@JsonIgnore
	private User user;
	private String postDetail;
	private String imgPath;
	@JsonIgnore
	private List<Report> reports = new ArrayList<Report>();
	@JsonIgnore
	private List<RequestCourse> requestCourses = new ArrayList<RequestCourse>();
	@JsonIgnore
	private List<ImgPost> imgPosts = new ArrayList<ImgPost>();
	@JsonIgnore
	private List<PostLike> postLikes = new ArrayList<PostLike>();
	@JsonIgnore
	private List<Comment> comments = new ArrayList<Comment>();
	@JsonIgnore
	private List<Bookmark> bookmarks = new ArrayList<Bookmark>();
	@JsonIgnore
	private List<Course> courses = new ArrayList<Course>();

	public Post() {
	}

	public Post(User user, String postDetail, String imgPath) {
		this.user = user;
		this.postDetail = postDetail;
		this.imgPath = imgPath;
	}

	public Post(Type type, User user, String postDetail, String imgPath, List<Report> reports, List<RequestCourse> requestcourses, List<ImgPost> imgposts,
			List<PostLike> postlikes, List<Comment> comments, List<Bookmark> bookmarks, List<Course> courses) {
		this.type = type;
		this.user = user;
		this.postDetail = postDetail;
		this.imgPath = imgPath;
		this.reports = reports;
		this.requestCourses = requestcourses;
		this.imgPosts = imgposts;
		this.postLikes = postlikes;
		this.comments = comments;
		this.bookmarks = bookmarks;
		this.courses = courses;
	}

	public int getPostId() {
		return postId;
	}

	public void setPostId(int postId) {
		this.postId = postId;
	}

	public Type getType() {
		return type;
	}

	public void setType(Type type) {
		this.type = type;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getPostDetail() {
		return postDetail;
	}

	public void setPostDetail(String postDetail) {
		this.postDetail = postDetail;
	}

	public String getImgPath() {
		return imgPath;
	}

	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}

	public List<Report> getReports() {
		return reports;
	}

	public void setReports(List<Report> reports) {
		this.reports = reports;
	}

	public List<RequestCourse> getRequestCourses() {
		return requestCourses;
	}

	public void setRequestCourses(List<RequestCourse> requestCourses) {
		this.requestCourses = requestCourses;
	}

	public List<ImgPost> getImgPosts() {
		return imgPosts;
	}

	public void setImgPosts(List<ImgPost> imgPosts) {
		this.imgPosts = imgPosts;
	}

	public List<PostLike> getPostLikes() {
		return postLikes;
	}

	public void setPostLikes(List<PostLike> postLikes) {
		this.postLikes = postLikes;
	}

	public List<Comment> getComments() {
		return comments;
	}

	public void setComments(List<Comment> comments) {
		this.comments = comments;
	}

	public List<Bookmark> getBookmarks() {
		return bookmarks;
	}

	public void setBookmarks(List<Bookmark> bookmarks) {
		this.bookmarks = bookmarks;
	}

	public List<Course> getCourses() {
		return courses;
	}

	public void setCourses(List<Course> courses) {
		this.courses = courses;
	}


}
